[2021-06-06 14:37:04,365] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: listar_arquivos_bucket_rox.list_keys 2021-06-06T14:37:03.107170+00:00 [queued]>
[2021-06-06 14:37:04,378] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: listar_arquivos_bucket_rox.list_keys 2021-06-06T14:37:03.107170+00:00 [queued]>
[2021-06-06 14:37:04,378] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 14:37:04,378] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-06 14:37:04,379] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 14:37:04,386] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): list_keys> on 2021-06-06T14:37:03.107170+00:00
[2021-06-06 14:37:04,390] {standard_task_runner.py:52} INFO - Started process 101 to run task
[2021-06-06 14:37:04,393] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'listar_arquivos_bucket_rox', 'list_keys', '2021-06-06T14:37:03.107170+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/listar_arquivos.py', '--cfg-path', '/tmp/tmpu7slv659', '--error-file', '/tmp/tmpr4aj3c7p']
[2021-06-06 14:37:04,393] {standard_task_runner.py:77} INFO - Job 8: Subtask list_keys
[2021-06-06 14:37:04,420] {logging_mixin.py:104} INFO - Running <TaskInstance: listar_arquivos_bucket_rox.list_keys 2021-06-06T14:37:03.107170+00:00 [running]> on host 21bd802337aa
[2021-06-06 14:37:04,455] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listar_arquivos_bucket_rox
AIRFLOW_CTX_TASK_ID=list_keys
AIRFLOW_CTX_EXECUTION_DATE=2021-06-06T14:37:03.107170+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-06T14:37:03.107170+00:00
[2021-06-06 14:37:04,461] {listar_arquivos.py:13} INFO - Listing Keys from roxproject
[2021-06-06 14:37:04,461] {base_aws.py:368} INFO - Airflow Connection: aws_conn_id=aws_credentials
[2021-06-06 14:37:04,467] {base_aws.py:170} INFO - Credentials retrieved from extra_config
[2021-06-06 14:37:04,467] {base_aws.py:87} INFO - Creating session with aws_access_key_id=AKIAQNT7WWEVKZQVCKMP region_name=None
[2021-06-06 14:37:04,480] {base_aws.py:157} INFO - role_arn is None
[2021-06-06 14:37:05,725] {listar_arquivos.py:16} INFO - - s3://roxproject/Person.Person.csv
[2021-06-06 14:37:05,725] {listar_arquivos.py:16} INFO - - s3://roxproject/Production.Product.csv
[2021-06-06 14:37:05,725] {listar_arquivos.py:16} INFO - - s3://roxproject/Sales.Customer.csv
[2021-06-06 14:37:05,726] {listar_arquivos.py:16} INFO - - s3://roxproject/Sales.SalesOrderDetail.csv
[2021-06-06 14:37:05,726] {listar_arquivos.py:16} INFO - - s3://roxproject/Sales.SalesOrderHeader.csv
[2021-06-06 14:37:05,726] {listar_arquivos.py:16} INFO - - s3://roxproject/Sales.SpecialOfferProduct.csv
[2021-06-06 14:37:05,729] {python.py:151} INFO - Done. Returned value was: None
[2021-06-06 14:37:05,750] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=listar_arquivos_bucket_rox, task_id=list_keys, execution_date=20210606T143703, start_date=20210606T143704, end_date=20210606T143705
[2021-06-06 14:37:05,805] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-06 14:37:05,850] {local_task_job.py:151} INFO - Task exited with return code 0
