[2021-06-06 22:55:54,345] {scheduler_job.py:182} INFO - Started process (PID=1221) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:55:54,345] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:55:54,346] {logging_mixin.py:104} INFO - [2021-06-06 22:55:54,346] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:55:54,351] {logging_mixin.py:104} INFO - [2021-06-06 22:55:54,351] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:55:54,352] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:55:54,368] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 22:56:25,204] {scheduler_job.py:182} INFO - Started process (PID=1310) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:56:25,205] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:56:25,205] {logging_mixin.py:104} INFO - [2021-06-06 22:56:25,205] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:56:25,209] {logging_mixin.py:104} INFO - [2021-06-06 22:56:25,209] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:56:25,210] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:56:25,225] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.024 seconds
[2021-06-06 22:56:55,735] {scheduler_job.py:182} INFO - Started process (PID=1396) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:56:55,737] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:56:55,737] {logging_mixin.py:104} INFO - [2021-06-06 22:56:55,737] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:56:55,741] {logging_mixin.py:104} INFO - [2021-06-06 22:56:55,740] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:56:55,741] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:56:55,755] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 22:57:26,310] {scheduler_job.py:182} INFO - Started process (PID=1465) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:57:26,311] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:57:26,311] {logging_mixin.py:104} INFO - [2021-06-06 22:57:26,311] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:57:26,314] {logging_mixin.py:104} INFO - [2021-06-06 22:57:26,313] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:57:26,314] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:57:26,325] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 22:57:57,151] {scheduler_job.py:182} INFO - Started process (PID=1551) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:57:57,152] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:57:57,152] {logging_mixin.py:104} INFO - [2021-06-06 22:57:57,152] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:57:57,156] {logging_mixin.py:104} INFO - [2021-06-06 22:57:57,155] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:57:57,156] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:57:57,174] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 22:58:27,464] {scheduler_job.py:182} INFO - Started process (PID=1638) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:58:27,464] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:58:27,465] {logging_mixin.py:104} INFO - [2021-06-06 22:58:27,465] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:58:27,468] {logging_mixin.py:104} INFO - [2021-06-06 22:58:27,468] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:58:27,469] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:58:27,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.020 seconds
[2021-06-06 22:58:58,238] {scheduler_job.py:182} INFO - Started process (PID=1708) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:58:58,239] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:58:58,239] {logging_mixin.py:104} INFO - [2021-06-06 22:58:58,239] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:58:58,242] {logging_mixin.py:104} INFO - [2021-06-06 22:58:58,242] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:58:58,243] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:58:58,255] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.020 seconds
[2021-06-06 22:59:28,667] {scheduler_job.py:182} INFO - Started process (PID=1796) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:59:28,668] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:59:28,668] {logging_mixin.py:104} INFO - [2021-06-06 22:59:28,668] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:59:28,671] {logging_mixin.py:104} INFO - [2021-06-06 22:59:28,671] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:59:28,671] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:59:28,683] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 22:59:59,321] {scheduler_job.py:182} INFO - Started process (PID=1876) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:59:59,322] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 22:59:59,322] {logging_mixin.py:104} INFO - [2021-06-06 22:59:59,322] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:59:59,325] {logging_mixin.py:104} INFO - [2021-06-06 22:59:59,324] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 22:59:59,325] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 22:59:59,338] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.020 seconds
[2021-06-06 23:00:30,037] {scheduler_job.py:182} INFO - Started process (PID=1952) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:00:30,038] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:00:30,038] {logging_mixin.py:104} INFO - [2021-06-06 23:00:30,038] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:00:30,042] {logging_mixin.py:104} INFO - [2021-06-06 23:00:30,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:00:30,042] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:00:30,057] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:01:00,445] {scheduler_job.py:182} INFO - Started process (PID=2039) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:01:00,448] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:01:00,449] {logging_mixin.py:104} INFO - [2021-06-06 23:01:00,449] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:01:00,461] {logging_mixin.py:104} INFO - [2021-06-06 23:01:00,459] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:01:00,462] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:01:00,484] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.046 seconds
[2021-06-06 23:01:31,384] {scheduler_job.py:182} INFO - Started process (PID=2119) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:01:31,385] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:01:31,385] {logging_mixin.py:104} INFO - [2021-06-06 23:01:31,385] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:01:31,388] {logging_mixin.py:104} INFO - [2021-06-06 23:01:31,387] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:01:31,388] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:01:31,401] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:02:02,083] {scheduler_job.py:182} INFO - Started process (PID=2195) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:02:02,084] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:02:02,084] {logging_mixin.py:104} INFO - [2021-06-06 23:02:02,084] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:02:02,087] {logging_mixin.py:104} INFO - [2021-06-06 23:02:02,086] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:02:02,087] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:02:02,099] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:02:32,905] {scheduler_job.py:182} INFO - Started process (PID=2282) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:02:32,906] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:02:32,906] {logging_mixin.py:104} INFO - [2021-06-06 23:02:32,906] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:02:32,910] {logging_mixin.py:104} INFO - [2021-06-06 23:02:32,909] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:02:32,910] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:02:32,927] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 23:03:03,380] {scheduler_job.py:182} INFO - Started process (PID=2358) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:03:03,381] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:03:03,382] {logging_mixin.py:104} INFO - [2021-06-06 23:03:03,382] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:03:03,385] {logging_mixin.py:104} INFO - [2021-06-06 23:03:03,385] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:03:03,386] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:03:03,400] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:03:33,659] {scheduler_job.py:182} INFO - Started process (PID=2437) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:03:33,659] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:03:33,660] {logging_mixin.py:104} INFO - [2021-06-06 23:03:33,660] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:03:33,662] {logging_mixin.py:104} INFO - [2021-06-06 23:03:33,662] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:03:33,662] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:03:33,675] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:04:04,254] {scheduler_job.py:182} INFO - Started process (PID=2523) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:04:04,256] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:04:04,258] {logging_mixin.py:104} INFO - [2021-06-06 23:04:04,257] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:04:04,267] {logging_mixin.py:104} INFO - [2021-06-06 23:04:04,266] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:04:04,268] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:04:04,293] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.045 seconds
[2021-06-06 23:04:34,631] {scheduler_job.py:182} INFO - Started process (PID=2592) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:04:34,631] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:04:34,632] {logging_mixin.py:104} INFO - [2021-06-06 23:04:34,632] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:04:34,635] {logging_mixin.py:104} INFO - [2021-06-06 23:04:34,635] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:04:34,635] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:04:34,647] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:05:05,039] {scheduler_job.py:182} INFO - Started process (PID=2679) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:05:05,039] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:05:05,040] {logging_mixin.py:104} INFO - [2021-06-06 23:05:05,039] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:05:05,042] {logging_mixin.py:104} INFO - [2021-06-06 23:05:05,042] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:05:05,042] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:05:05,053] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:05:35,657] {scheduler_job.py:182} INFO - Started process (PID=2766) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:05:35,657] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:05:35,658] {logging_mixin.py:104} INFO - [2021-06-06 23:05:35,658] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:05:35,662] {logging_mixin.py:104} INFO - [2021-06-06 23:05:35,661] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:05:35,662] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:05:35,679] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.025 seconds
[2021-06-06 23:06:05,991] {scheduler_job.py:182} INFO - Started process (PID=2835) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:06:05,994] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:06:05,995] {logging_mixin.py:104} INFO - [2021-06-06 23:06:05,995] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:06:06,008] {logging_mixin.py:104} INFO - [2021-06-06 23:06:06,006] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:06:06,009] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:06:06,031] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.047 seconds
[2021-06-06 23:06:36,636] {scheduler_job.py:182} INFO - Started process (PID=2921) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:06:36,637] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:06:36,637] {logging_mixin.py:104} INFO - [2021-06-06 23:06:36,637] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:06:36,640] {logging_mixin.py:104} INFO - [2021-06-06 23:06:36,639] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:06:36,640] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:06:36,651] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:07:07,418] {scheduler_job.py:182} INFO - Started process (PID=3008) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:07:07,418] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:07:07,419] {logging_mixin.py:104} INFO - [2021-06-06 23:07:07,419] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:07:07,423] {logging_mixin.py:104} INFO - [2021-06-06 23:07:07,422] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:07:07,423] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:07:07,437] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:07:38,130] {scheduler_job.py:182} INFO - Started process (PID=3077) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:07:38,130] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:07:38,131] {logging_mixin.py:104} INFO - [2021-06-06 23:07:38,131] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:07:38,133] {logging_mixin.py:104} INFO - [2021-06-06 23:07:38,133] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:07:38,133] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:07:38,145] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:08:08,399] {scheduler_job.py:182} INFO - Started process (PID=3165) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:08:08,402] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:08:08,405] {logging_mixin.py:104} INFO - [2021-06-06 23:08:08,404] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:08:08,413] {logging_mixin.py:104} INFO - [2021-06-06 23:08:08,412] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:08:08,414] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:08:08,431] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.041 seconds
[2021-06-06 23:08:39,205] {scheduler_job.py:182} INFO - Started process (PID=3244) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:08:39,206] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:08:39,206] {logging_mixin.py:104} INFO - [2021-06-06 23:08:39,206] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:08:39,209] {logging_mixin.py:104} INFO - [2021-06-06 23:08:39,208] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:08:39,209] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:08:39,225] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:09:09,517] {scheduler_job.py:182} INFO - Started process (PID=3321) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:09:09,517] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:09:09,518] {logging_mixin.py:104} INFO - [2021-06-06 23:09:09,518] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:09:09,523] {logging_mixin.py:104} INFO - [2021-06-06 23:09:09,522] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:09:09,523] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:09:09,537] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:09:40,000] {scheduler_job.py:182} INFO - Started process (PID=3409) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:09:40,001] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:09:40,001] {logging_mixin.py:104} INFO - [2021-06-06 23:09:40,001] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:09:40,004] {logging_mixin.py:104} INFO - [2021-06-06 23:09:40,003] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:09:40,004] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:09:40,019] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.021 seconds
[2021-06-06 23:10:10,469] {scheduler_job.py:182} INFO - Started process (PID=3479) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:10:10,472] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:10:10,474] {logging_mixin.py:104} INFO - [2021-06-06 23:10:10,473] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:10:10,482] {logging_mixin.py:104} INFO - [2021-06-06 23:10:10,480] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:10:10,482] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:10:10,499] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.038 seconds
[2021-06-06 23:10:41,278] {scheduler_job.py:182} INFO - Started process (PID=3566) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:10:41,279] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:10:41,279] {logging_mixin.py:104} INFO - [2021-06-06 23:10:41,279] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:10:41,282] {logging_mixin.py:104} INFO - [2021-06-06 23:10:41,282] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:10:41,282] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:10:41,294] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:11:11,643] {scheduler_job.py:182} INFO - Started process (PID=3653) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:11:11,646] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:11:11,647] {logging_mixin.py:104} INFO - [2021-06-06 23:11:11,647] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:11:11,660] {logging_mixin.py:104} INFO - [2021-06-06 23:11:11,658] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:11:11,661] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:11:11,680] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.045 seconds
[2021-06-06 23:11:42,264] {scheduler_job.py:182} INFO - Started process (PID=3724) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:11:42,268] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:11:42,269] {logging_mixin.py:104} INFO - [2021-06-06 23:11:42,269] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:11:42,279] {logging_mixin.py:104} INFO - [2021-06-06 23:11:42,277] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:11:42,280] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:11:42,307] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.049 seconds
[2021-06-06 23:12:12,868] {scheduler_job.py:182} INFO - Started process (PID=3810) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:12:12,869] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:12:12,869] {logging_mixin.py:104} INFO - [2021-06-06 23:12:12,869] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:12:12,873] {logging_mixin.py:104} INFO - [2021-06-06 23:12:12,872] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:12:12,873] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:12:12,890] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.025 seconds
[2021-06-06 23:12:43,063] {scheduler_job.py:182} INFO - Started process (PID=3897) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:12:43,064] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:12:43,064] {logging_mixin.py:104} INFO - [2021-06-06 23:12:43,064] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:12:43,068] {logging_mixin.py:104} INFO - [2021-06-06 23:12:43,067] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:12:43,068] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:12:43,079] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:13:13,453] {scheduler_job.py:182} INFO - Started process (PID=3966) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:13:13,454] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:13:13,454] {logging_mixin.py:104} INFO - [2021-06-06 23:13:13,454] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:13:13,458] {logging_mixin.py:104} INFO - [2021-06-06 23:13:13,457] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:13:13,458] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:13:13,472] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:13:44,290] {scheduler_job.py:182} INFO - Started process (PID=4053) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:13:44,291] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:13:44,292] {logging_mixin.py:104} INFO - [2021-06-06 23:13:44,292] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:13:44,297] {logging_mixin.py:104} INFO - [2021-06-06 23:13:44,296] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:13:44,298] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:13:44,319] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.033 seconds
[2021-06-06 23:14:14,736] {scheduler_job.py:182} INFO - Started process (PID=4131) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:14:14,737] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:14:14,737] {logging_mixin.py:104} INFO - [2021-06-06 23:14:14,737] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:14:14,740] {logging_mixin.py:104} INFO - [2021-06-06 23:14:14,740] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:14:14,740] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:14:14,752] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:14:45,123] {scheduler_job.py:182} INFO - Started process (PID=4208) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:14:45,124] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:14:45,124] {logging_mixin.py:104} INFO - [2021-06-06 23:14:45,124] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:14:45,127] {logging_mixin.py:104} INFO - [2021-06-06 23:14:45,127] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:14:45,127] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:14:45,139] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:15:15,804] {scheduler_job.py:182} INFO - Started process (PID=4296) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:15:15,804] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:15:15,805] {logging_mixin.py:104} INFO - [2021-06-06 23:15:15,804] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:15:15,807] {logging_mixin.py:104} INFO - [2021-06-06 23:15:15,807] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:15:15,807] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:15:15,819] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:15:46,153] {scheduler_job.py:182} INFO - Started process (PID=4366) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:15:46,154] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:15:46,154] {logging_mixin.py:104} INFO - [2021-06-06 23:15:46,154] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:15:46,158] {logging_mixin.py:104} INFO - [2021-06-06 23:15:46,157] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:15:46,158] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:15:46,172] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:16:16,550] {scheduler_job.py:182} INFO - Started process (PID=4453) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:16:16,551] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:16:16,551] {logging_mixin.py:104} INFO - [2021-06-06 23:16:16,551] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:16:16,554] {logging_mixin.py:104} INFO - [2021-06-06 23:16:16,553] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:16:16,554] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:16:16,564] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.016 seconds
[2021-06-06 23:16:47,143] {scheduler_job.py:182} INFO - Started process (PID=4539) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:16:47,144] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:16:47,145] {logging_mixin.py:104} INFO - [2021-06-06 23:16:47,144] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:16:47,147] {logging_mixin.py:104} INFO - [2021-06-06 23:16:47,147] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:16:47,148] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:16:47,161] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.020 seconds
[2021-06-06 23:17:26,281] {scheduler_job.py:182} INFO - Started process (PID=32) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:17:26,282] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:17:26,283] {logging_mixin.py:104} INFO - [2021-06-06 23:17:26,282] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:17:26,286] {logging_mixin.py:104} INFO - [2021-06-06 23:17:26,286] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:17:26,287] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:17:26,302] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:17:56,778] {scheduler_job.py:182} INFO - Started process (PID=101) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:17:56,780] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:17:56,781] {logging_mixin.py:104} INFO - [2021-06-06 23:17:56,781] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:17:56,787] {logging_mixin.py:104} INFO - [2021-06-06 23:17:56,786] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:17:56,787] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:17:56,802] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.031 seconds
[2021-06-06 23:18:27,051] {scheduler_job.py:182} INFO - Started process (PID=187) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:18:27,052] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:18:27,052] {logging_mixin.py:104} INFO - [2021-06-06 23:18:27,052] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:18:27,055] {logging_mixin.py:104} INFO - [2021-06-06 23:18:27,055] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:18:27,055] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:18:27,067] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:18:57,828] {scheduler_job.py:182} INFO - Started process (PID=273) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:18:57,829] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:18:57,829] {logging_mixin.py:104} INFO - [2021-06-06 23:18:57,829] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:18:57,832] {logging_mixin.py:104} INFO - [2021-06-06 23:18:57,831] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:18:57,832] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:18:57,844] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:19:28,548] {scheduler_job.py:182} INFO - Started process (PID=342) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:19:28,548] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:19:28,549] {logging_mixin.py:104} INFO - [2021-06-06 23:19:28,549] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:19:28,552] {logging_mixin.py:104} INFO - [2021-06-06 23:19:28,552] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:19:28,553] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:19:28,566] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.021 seconds
[2021-06-06 23:19:59,298] {scheduler_job.py:182} INFO - Started process (PID=428) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:19:59,299] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:19:59,299] {logging_mixin.py:104} INFO - [2021-06-06 23:19:59,299] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:19:59,302] {logging_mixin.py:104} INFO - [2021-06-06 23:19:59,302] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:19:59,302] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:19:59,315] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:20:30,232] {scheduler_job.py:182} INFO - Started process (PID=514) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:20:30,235] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:20:30,236] {logging_mixin.py:104} INFO - [2021-06-06 23:20:30,236] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:20:30,245] {logging_mixin.py:104} INFO - [2021-06-06 23:20:30,244] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:20:30,246] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:20:30,265] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.040 seconds
[2021-06-06 23:21:08,078] {scheduler_job.py:182} INFO - Started process (PID=32) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:21:08,079] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:21:08,080] {logging_mixin.py:104} INFO - [2021-06-06 23:21:08,079] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:21:08,083] {logging_mixin.py:104} INFO - [2021-06-06 23:21:08,082] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:21:08,083] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:21:08,097] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:21:38,531] {scheduler_job.py:182} INFO - Started process (PID=104) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:21:38,531] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:21:38,532] {logging_mixin.py:104} INFO - [2021-06-06 23:21:38,532] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:21:38,536] {logging_mixin.py:104} INFO - [2021-06-06 23:21:38,535] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:21:38,536] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:21:38,550] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:22:09,231] {scheduler_job.py:182} INFO - Started process (PID=201) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:22:09,232] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:22:09,232] {logging_mixin.py:104} INFO - [2021-06-06 23:22:09,232] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:22:09,235] {logging_mixin.py:104} INFO - [2021-06-06 23:22:09,235] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:22:09,236] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:22:09,251] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:22:40,229] {scheduler_job.py:182} INFO - Started process (PID=287) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:22:40,230] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:22:40,230] {logging_mixin.py:104} INFO - [2021-06-06 23:22:40,230] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:22:40,233] {logging_mixin.py:104} INFO - [2021-06-06 23:22:40,233] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:22:40,233] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:22:40,245] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:23:11,115] {scheduler_job.py:182} INFO - Started process (PID=356) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:23:11,116] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:23:11,117] {logging_mixin.py:104} INFO - [2021-06-06 23:23:11,117] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:23:11,122] {logging_mixin.py:104} INFO - [2021-06-06 23:23:11,121] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:23:11,122] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:23:11,137] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.027 seconds
[2021-06-06 23:23:41,994] {scheduler_job.py:182} INFO - Started process (PID=444) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:23:41,994] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:23:41,995] {logging_mixin.py:104} INFO - [2021-06-06 23:23:41,995] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:23:41,998] {logging_mixin.py:104} INFO - [2021-06-06 23:23:41,997] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:23:41,998] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:23:42,008] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:24:12,918] {scheduler_job.py:182} INFO - Started process (PID=531) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:24:12,919] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:24:12,919] {logging_mixin.py:104} INFO - [2021-06-06 23:24:12,919] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:24:12,922] {logging_mixin.py:104} INFO - [2021-06-06 23:24:12,922] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:24:12,922] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:24:12,935] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:24:43,743] {scheduler_job.py:182} INFO - Started process (PID=32) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:24:43,744] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:24:43,744] {logging_mixin.py:104} INFO - [2021-06-06 23:24:43,744] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:24:43,748] {logging_mixin.py:104} INFO - [2021-06-06 23:24:43,747] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:24:43,748] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:24:43,763] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:25:14,285] {scheduler_job.py:182} INFO - Started process (PID=100) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:25:14,286] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:25:14,286] {logging_mixin.py:104} INFO - [2021-06-06 23:25:14,286] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:25:14,290] {logging_mixin.py:104} INFO - [2021-06-06 23:25:14,289] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:25:14,290] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:25:14,304] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:25:44,439] {scheduler_job.py:182} INFO - Started process (PID=187) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:25:44,440] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:25:44,440] {logging_mixin.py:104} INFO - [2021-06-06 23:25:44,440] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:25:44,443] {logging_mixin.py:104} INFO - [2021-06-06 23:25:44,442] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:25:44,443] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:25:44,455] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:26:15,294] {scheduler_job.py:182} INFO - Started process (PID=274) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:26:15,294] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:26:15,295] {logging_mixin.py:104} INFO - [2021-06-06 23:26:15,295] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:26:15,298] {logging_mixin.py:104} INFO - [2021-06-06 23:26:15,298] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:26:15,299] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:26:15,313] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:26:46,184] {scheduler_job.py:182} INFO - Started process (PID=343) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:26:46,185] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:26:46,186] {logging_mixin.py:104} INFO - [2021-06-06 23:26:46,186] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:26:46,190] {logging_mixin.py:104} INFO - [2021-06-06 23:26:46,189] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:26:46,190] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:26:46,204] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:27:16,316] {scheduler_job.py:182} INFO - Started process (PID=438) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:27:16,317] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:27:16,317] {logging_mixin.py:104} INFO - [2021-06-06 23:27:16,317] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:27:16,321] {logging_mixin.py:104} INFO - [2021-06-06 23:27:16,320] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:27:16,321] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:27:16,340] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.028 seconds
[2021-06-06 23:27:47,105] {scheduler_job.py:182} INFO - Started process (PID=527) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:27:47,106] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:27:47,106] {logging_mixin.py:104} INFO - [2021-06-06 23:27:47,106] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:27:47,110] {logging_mixin.py:104} INFO - [2021-06-06 23:27:47,109] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:27:47,110] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:27:47,129] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 23:28:17,916] {scheduler_job.py:182} INFO - Started process (PID=596) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:28:17,917] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:28:17,917] {logging_mixin.py:104} INFO - [2021-06-06 23:28:17,917] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:28:17,920] {logging_mixin.py:104} INFO - [2021-06-06 23:28:17,919] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:28:17,920] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:28:17,935] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.021 seconds
[2021-06-06 23:28:48,917] {scheduler_job.py:182} INFO - Started process (PID=683) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:28:48,919] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:28:48,921] {logging_mixin.py:104} INFO - [2021-06-06 23:28:48,920] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:28:48,931] {logging_mixin.py:104} INFO - [2021-06-06 23:28:48,929] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:28:48,932] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:28:48,953] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.046 seconds
[2021-06-06 23:29:19,779] {scheduler_job.py:182} INFO - Started process (PID=769) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:29:19,779] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:29:19,780] {logging_mixin.py:104} INFO - [2021-06-06 23:29:19,780] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:29:19,783] {logging_mixin.py:104} INFO - [2021-06-06 23:29:19,783] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:29:19,784] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:29:19,798] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:29:50,499] {scheduler_job.py:182} INFO - Started process (PID=839) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:29:50,500] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:29:50,500] {logging_mixin.py:104} INFO - [2021-06-06 23:29:50,500] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:29:50,503] {logging_mixin.py:104} INFO - [2021-06-06 23:29:50,502] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:29:50,503] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:29:50,516] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:30:20,554] {scheduler_job.py:182} INFO - Started process (PID=925) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:30:20,555] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:30:20,555] {logging_mixin.py:104} INFO - [2021-06-06 23:30:20,555] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:30:20,559] {logging_mixin.py:104} INFO - [2021-06-06 23:30:20,558] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:30:20,559] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:30:20,577] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 23:30:51,436] {scheduler_job.py:182} INFO - Started process (PID=1011) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:30:51,437] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:30:51,437] {logging_mixin.py:104} INFO - [2021-06-06 23:30:51,437] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:30:51,440] {logging_mixin.py:104} INFO - [2021-06-06 23:30:51,439] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:30:51,440] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:30:51,451] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:31:22,277] {scheduler_job.py:182} INFO - Started process (PID=1081) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:31:22,279] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:31:22,281] {logging_mixin.py:104} INFO - [2021-06-06 23:31:22,281] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:31:22,293] {logging_mixin.py:104} INFO - [2021-06-06 23:31:22,291] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:31:22,294] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:31:22,316] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.047 seconds
[2021-06-06 23:31:53,122] {scheduler_job.py:182} INFO - Started process (PID=1167) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:31:53,123] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:31:53,123] {logging_mixin.py:104} INFO - [2021-06-06 23:31:53,123] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:31:53,126] {logging_mixin.py:104} INFO - [2021-06-06 23:31:53,125] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:31:53,126] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:31:53,138] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:32:23,906] {scheduler_job.py:182} INFO - Started process (PID=1254) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:32:23,907] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:32:23,907] {logging_mixin.py:104} INFO - [2021-06-06 23:32:23,907] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:32:23,910] {logging_mixin.py:104} INFO - [2021-06-06 23:32:23,910] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:32:23,911] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:32:23,923] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:32:53,949] {scheduler_job.py:182} INFO - Started process (PID=1323) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:32:53,949] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:32:53,950] {logging_mixin.py:104} INFO - [2021-06-06 23:32:53,950] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:32:53,953] {logging_mixin.py:104} INFO - [2021-06-06 23:32:53,953] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:32:53,953] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:32:53,967] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.021 seconds
[2021-06-06 23:33:24,808] {scheduler_job.py:182} INFO - Started process (PID=1409) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:33:24,808] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:33:24,812] {logging_mixin.py:104} INFO - [2021-06-06 23:33:24,812] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:33:24,817] {logging_mixin.py:104} INFO - [2021-06-06 23:33:24,816] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:33:24,817] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:33:24,841] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.036 seconds
[2021-06-06 23:33:55,724] {scheduler_job.py:182} INFO - Started process (PID=1495) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:33:55,725] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:33:55,725] {logging_mixin.py:104} INFO - [2021-06-06 23:33:55,725] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:33:55,728] {logging_mixin.py:104} INFO - [2021-06-06 23:33:55,727] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:33:55,728] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:33:55,739] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:34:26,541] {scheduler_job.py:182} INFO - Started process (PID=1564) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:34:26,542] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:34:26,542] {logging_mixin.py:104} INFO - [2021-06-06 23:34:26,542] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:34:26,546] {logging_mixin.py:104} INFO - [2021-06-06 23:34:26,546] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:34:26,547] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:34:26,564] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.025 seconds
[2021-06-06 23:34:57,345] {scheduler_job.py:182} INFO - Started process (PID=1650) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:34:57,346] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:34:57,346] {logging_mixin.py:104} INFO - [2021-06-06 23:34:57,346] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:34:57,350] {logging_mixin.py:104} INFO - [2021-06-06 23:34:57,349] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:34:57,350] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:34:57,381] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.038 seconds
[2021-06-06 23:35:28,229] {scheduler_job.py:182} INFO - Started process (PID=1736) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:35:28,230] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:35:28,230] {logging_mixin.py:104} INFO - [2021-06-06 23:35:28,230] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:35:28,232] {logging_mixin.py:104} INFO - [2021-06-06 23:35:28,232] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:35:28,233] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:35:28,244] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:35:59,134] {scheduler_job.py:182} INFO - Started process (PID=1806) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:35:59,135] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:35:59,135] {logging_mixin.py:104} INFO - [2021-06-06 23:35:59,135] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:35:59,139] {logging_mixin.py:104} INFO - [2021-06-06 23:35:59,138] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:35:59,139] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:35:59,157] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 23:36:30,037] {scheduler_job.py:182} INFO - Started process (PID=1894) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:36:30,037] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:36:30,038] {logging_mixin.py:104} INFO - [2021-06-06 23:36:30,038] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:36:30,042] {logging_mixin.py:104} INFO - [2021-06-06 23:36:30,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:36:30,042] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:36:30,060] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.027 seconds
[2021-06-06 23:37:00,787] {scheduler_job.py:182} INFO - Started process (PID=1980) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:37:00,789] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:37:00,789] {logging_mixin.py:104} INFO - [2021-06-06 23:37:00,789] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:37:00,793] {logging_mixin.py:104} INFO - [2021-06-06 23:37:00,792] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:37:00,793] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:37:00,808] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:37:31,767] {scheduler_job.py:182} INFO - Started process (PID=2049) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:37:31,768] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:37:31,768] {logging_mixin.py:104} INFO - [2021-06-06 23:37:31,768] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:37:31,772] {logging_mixin.py:104} INFO - [2021-06-06 23:37:31,771] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:37:31,772] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:37:31,787] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:38:02,540] {scheduler_job.py:182} INFO - Started process (PID=2136) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:38:02,541] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:38:02,541] {logging_mixin.py:104} INFO - [2021-06-06 23:38:02,541] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:38:02,545] {logging_mixin.py:104} INFO - [2021-06-06 23:38:02,544] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:38:02,545] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:38:02,568] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.030 seconds
[2021-06-06 23:38:33,442] {scheduler_job.py:182} INFO - Started process (PID=2223) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:38:33,443] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:38:33,443] {logging_mixin.py:104} INFO - [2021-06-06 23:38:33,443] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:38:33,447] {logging_mixin.py:104} INFO - [2021-06-06 23:38:33,446] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:38:33,447] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:38:33,465] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 23:39:04,353] {scheduler_job.py:182} INFO - Started process (PID=2292) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:39:04,353] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:39:04,354] {logging_mixin.py:104} INFO - [2021-06-06 23:39:04,354] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:39:04,356] {logging_mixin.py:104} INFO - [2021-06-06 23:39:04,356] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:39:04,356] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:39:04,368] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:39:35,279] {scheduler_job.py:182} INFO - Started process (PID=2378) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:39:35,279] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:39:35,280] {logging_mixin.py:104} INFO - [2021-06-06 23:39:35,280] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:39:35,283] {logging_mixin.py:104} INFO - [2021-06-06 23:39:35,282] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:39:35,283] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:39:35,293] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.016 seconds
[2021-06-06 23:40:05,349] {scheduler_job.py:182} INFO - Started process (PID=2464) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:40:05,350] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:40:05,353] {logging_mixin.py:104} INFO - [2021-06-06 23:40:05,353] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:40:05,356] {logging_mixin.py:104} INFO - [2021-06-06 23:40:05,356] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:40:05,357] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:40:05,369] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:40:36,235] {scheduler_job.py:182} INFO - Started process (PID=2534) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:40:36,236] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:40:36,237] {logging_mixin.py:104} INFO - [2021-06-06 23:40:36,236] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:40:36,240] {logging_mixin.py:104} INFO - [2021-06-06 23:40:36,239] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:40:36,240] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:40:36,257] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.024 seconds
[2021-06-06 23:41:07,057] {scheduler_job.py:182} INFO - Started process (PID=2620) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:41:07,058] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:41:07,058] {logging_mixin.py:104} INFO - [2021-06-06 23:41:07,058] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:41:07,061] {logging_mixin.py:104} INFO - [2021-06-06 23:41:07,060] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:41:07,062] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:41:07,073] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:41:37,919] {scheduler_job.py:182} INFO - Started process (PID=2708) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:41:37,921] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:41:37,923] {logging_mixin.py:104} INFO - [2021-06-06 23:41:37,922] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:41:37,935] {logging_mixin.py:104} INFO - [2021-06-06 23:41:37,933] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:41:37,935] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:41:37,957] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.046 seconds
[2021-06-06 23:42:08,658] {scheduler_job.py:182} INFO - Started process (PID=2777) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:42:08,658] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:42:08,659] {logging_mixin.py:104} INFO - [2021-06-06 23:42:08,659] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:42:08,663] {logging_mixin.py:104} INFO - [2021-06-06 23:42:08,662] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:42:08,663] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:42:08,678] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.024 seconds
[2021-06-06 23:42:39,408] {scheduler_job.py:182} INFO - Started process (PID=2864) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:42:39,409] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:42:39,409] {logging_mixin.py:104} INFO - [2021-06-06 23:42:39,409] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:42:39,412] {logging_mixin.py:104} INFO - [2021-06-06 23:42:39,411] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:42:39,412] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:42:39,423] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:43:10,277] {scheduler_job.py:182} INFO - Started process (PID=2951) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:43:10,278] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:43:10,279] {logging_mixin.py:104} INFO - [2021-06-06 23:43:10,279] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:43:10,282] {logging_mixin.py:104} INFO - [2021-06-06 23:43:10,282] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:43:10,282] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:43:10,301] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.027 seconds
[2021-06-06 23:43:41,269] {scheduler_job.py:182} INFO - Started process (PID=3020) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:43:41,269] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:43:41,270] {logging_mixin.py:104} INFO - [2021-06-06 23:43:41,270] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:43:41,274] {logging_mixin.py:104} INFO - [2021-06-06 23:43:41,274] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:43:41,275] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:43:41,295] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.029 seconds
[2021-06-06 23:44:12,156] {scheduler_job.py:182} INFO - Started process (PID=3108) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:44:12,157] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:44:12,157] {logging_mixin.py:104} INFO - [2021-06-06 23:44:12,157] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:44:12,160] {logging_mixin.py:104} INFO - [2021-06-06 23:44:12,160] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:44:12,161] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:44:12,177] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:44:43,116] {scheduler_job.py:182} INFO - Started process (PID=3194) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:44:43,117] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:44:43,117] {logging_mixin.py:104} INFO - [2021-06-06 23:44:43,117] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:44:43,121] {logging_mixin.py:104} INFO - [2021-06-06 23:44:43,120] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:44:43,121] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:44:43,133] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:45:14,100] {scheduler_job.py:182} INFO - Started process (PID=3265) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:45:14,101] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:45:14,101] {logging_mixin.py:104} INFO - [2021-06-06 23:45:14,101] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:45:14,104] {logging_mixin.py:104} INFO - [2021-06-06 23:45:14,103] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:45:14,104] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:45:14,117] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:45:45,083] {scheduler_job.py:182} INFO - Started process (PID=3351) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:45:45,083] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:45:45,084] {logging_mixin.py:104} INFO - [2021-06-06 23:45:45,084] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:45:45,087] {logging_mixin.py:104} INFO - [2021-06-06 23:45:45,087] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:45:45,088] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:45:45,103] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:46:15,976] {scheduler_job.py:182} INFO - Started process (PID=3438) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:46:15,977] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:46:15,978] {logging_mixin.py:104} INFO - [2021-06-06 23:46:15,977] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:46:15,982] {logging_mixin.py:104} INFO - [2021-06-06 23:46:15,981] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:46:15,982] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:46:15,997] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:46:46,839] {scheduler_job.py:182} INFO - Started process (PID=3507) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:46:46,841] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:46:46,841] {logging_mixin.py:104} INFO - [2021-06-06 23:46:46,841] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:46:46,846] {logging_mixin.py:104} INFO - [2021-06-06 23:46:46,845] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:46:46,846] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:46:46,864] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.028 seconds
[2021-06-06 23:47:17,597] {scheduler_job.py:182} INFO - Started process (PID=3594) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:47:17,598] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:47:17,598] {logging_mixin.py:104} INFO - [2021-06-06 23:47:17,598] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:47:17,603] {logging_mixin.py:104} INFO - [2021-06-06 23:47:17,602] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:47:17,603] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:47:17,626] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.032 seconds
[2021-06-06 23:47:48,462] {scheduler_job.py:182} INFO - Started process (PID=3680) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:47:48,463] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:47:48,463] {logging_mixin.py:104} INFO - [2021-06-06 23:47:48,463] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:47:48,467] {logging_mixin.py:104} INFO - [2021-06-06 23:47:48,466] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:47:48,467] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:47:48,484] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.025 seconds
[2021-06-06 23:48:18,991] {scheduler_job.py:182} INFO - Started process (PID=3750) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:48:18,992] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:48:18,993] {logging_mixin.py:104} INFO - [2021-06-06 23:48:18,993] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:48:18,997] {logging_mixin.py:104} INFO - [2021-06-06 23:48:18,996] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:48:18,998] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:48:19,020] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.031 seconds
[2021-06-06 23:48:49,956] {scheduler_job.py:182} INFO - Started process (PID=3837) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:48:49,957] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:48:49,957] {logging_mixin.py:104} INFO - [2021-06-06 23:48:49,957] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:48:49,959] {logging_mixin.py:104} INFO - [2021-06-06 23:48:49,959] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:48:49,960] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:48:49,970] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.016 seconds
[2021-06-06 23:49:20,855] {scheduler_job.py:182} INFO - Started process (PID=3924) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:49:20,857] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:49:20,859] {logging_mixin.py:104} INFO - [2021-06-06 23:49:20,858] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:49:20,871] {logging_mixin.py:104} INFO - [2021-06-06 23:49:20,869] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:49:20,872] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:49:20,893] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.045 seconds
[2021-06-06 23:49:51,818] {scheduler_job.py:182} INFO - Started process (PID=3993) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:49:51,819] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:49:51,819] {logging_mixin.py:104} INFO - [2021-06-06 23:49:51,819] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:49:51,823] {logging_mixin.py:104} INFO - [2021-06-06 23:49:51,822] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:49:51,823] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:49:51,838] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:50:21,904] {scheduler_job.py:182} INFO - Started process (PID=4080) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:50:21,905] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:50:21,906] {logging_mixin.py:104} INFO - [2021-06-06 23:50:21,905] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:50:21,910] {logging_mixin.py:104} INFO - [2021-06-06 23:50:21,909] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:50:21,910] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:50:21,930] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.028 seconds
[2021-06-06 23:50:51,976] {scheduler_job.py:182} INFO - Started process (PID=4166) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:50:51,977] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:50:51,977] {logging_mixin.py:104} INFO - [2021-06-06 23:50:51,977] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:50:51,980] {logging_mixin.py:104} INFO - [2021-06-06 23:50:51,979] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:50:51,980] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:50:51,992] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.018 seconds
[2021-06-06 23:51:22,645] {scheduler_job.py:182} INFO - Started process (PID=4236) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:51:22,645] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:51:22,646] {logging_mixin.py:104} INFO - [2021-06-06 23:51:22,646] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:51:22,650] {logging_mixin.py:104} INFO - [2021-06-06 23:51:22,649] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:51:22,651] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:51:22,665] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:51:53,669] {scheduler_job.py:182} INFO - Started process (PID=4322) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:51:53,670] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:51:53,671] {logging_mixin.py:104} INFO - [2021-06-06 23:51:53,671] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:51:53,674] {logging_mixin.py:104} INFO - [2021-06-06 23:51:53,673] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:51:53,674] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:51:53,689] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:52:23,906] {scheduler_job.py:182} INFO - Started process (PID=4409) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:52:23,907] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:52:23,907] {logging_mixin.py:104} INFO - [2021-06-06 23:52:23,907] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:52:23,910] {logging_mixin.py:104} INFO - [2021-06-06 23:52:23,910] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:52:23,911] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:52:23,924] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.020 seconds
[2021-06-06 23:52:54,128] {scheduler_job.py:182} INFO - Started process (PID=4480) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:52:54,129] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:52:54,130] {logging_mixin.py:104} INFO - [2021-06-06 23:52:54,130] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:52:54,133] {logging_mixin.py:104} INFO - [2021-06-06 23:52:54,132] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:52:54,133] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:52:54,152] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.026 seconds
[2021-06-06 23:53:24,183] {scheduler_job.py:182} INFO - Started process (PID=4567) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:53:24,184] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:53:24,184] {logging_mixin.py:104} INFO - [2021-06-06 23:53:24,184] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:53:24,188] {logging_mixin.py:104} INFO - [2021-06-06 23:53:24,187] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:53:24,188] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:53:24,203] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.023 seconds
[2021-06-06 23:53:54,244] {scheduler_job.py:182} INFO - Started process (PID=4636) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:53:54,244] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:53:54,245] {logging_mixin.py:104} INFO - [2021-06-06 23:53:54,245] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:53:54,248] {logging_mixin.py:104} INFO - [2021-06-06 23:53:54,248] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:53:54,248] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:53:54,263] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.022 seconds
[2021-06-06 23:54:24,918] {scheduler_job.py:182} INFO - Started process (PID=4722) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:54:24,918] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:54:24,919] {logging_mixin.py:104} INFO - [2021-06-06 23:54:24,919] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:54:24,922] {logging_mixin.py:104} INFO - [2021-06-06 23:54:24,922] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:54:24,923] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:54:24,936] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.020 seconds
[2021-06-06 23:54:55,864] {scheduler_job.py:182} INFO - Started process (PID=4808) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:54:55,865] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:54:55,866] {logging_mixin.py:104} INFO - [2021-06-06 23:54:55,865] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:54:55,868] {logging_mixin.py:104} INFO - [2021-06-06 23:54:55,868] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:54:55,868] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:54:55,880] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:55:25,936] {scheduler_job.py:182} INFO - Started process (PID=4878) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:55:25,937] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:55:25,937] {logging_mixin.py:104} INFO - [2021-06-06 23:55:25,937] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:55:25,941] {logging_mixin.py:104} INFO - [2021-06-06 23:55:25,940] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:55:25,941] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:55:25,984] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.050 seconds
[2021-06-06 23:55:56,106] {scheduler_job.py:182} INFO - Started process (PID=4965) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:55:56,109] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:55:56,110] {logging_mixin.py:104} INFO - [2021-06-06 23:55:56,110] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:55:56,121] {logging_mixin.py:104} INFO - [2021-06-06 23:55:56,119] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:55:56,122] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:55:56,146] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.048 seconds
[2021-06-06 23:56:27,145] {scheduler_job.py:182} INFO - Started process (PID=5052) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:56:27,146] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:56:27,146] {logging_mixin.py:104} INFO - [2021-06-06 23:56:27,146] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:56:27,149] {logging_mixin.py:104} INFO - [2021-06-06 23:56:27,149] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:56:27,149] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:56:27,161] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.017 seconds
[2021-06-06 23:56:57,843] {scheduler_job.py:182} INFO - Started process (PID=5122) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:56:57,844] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:56:57,845] {logging_mixin.py:104} INFO - [2021-06-06 23:56:57,845] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:56:57,849] {logging_mixin.py:104} INFO - [2021-06-06 23:56:57,848] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:56:57,849] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:56:57,871] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.032 seconds
[2021-06-06 23:57:28,140] {scheduler_job.py:182} INFO - Started process (PID=5208) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:57:28,141] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:57:28,141] {logging_mixin.py:104} INFO - [2021-06-06 23:57:28,141] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:57:28,145] {logging_mixin.py:104} INFO - [2021-06-06 23:57:28,144] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:57:28,145] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:57:28,161] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.024 seconds
[2021-06-06 23:57:58,174] {scheduler_job.py:182} INFO - Started process (PID=5288) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:57:58,175] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:57:58,175] {logging_mixin.py:104} INFO - [2021-06-06 23:57:58,175] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:57:58,178] {logging_mixin.py:104} INFO - [2021-06-06 23:57:58,177] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-06 23:57:58,178] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:57:58,192] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:58:28,945] {scheduler_job.py:182} INFO - Started process (PID=5364) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:58:28,946] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:58:28,947] {logging_mixin.py:104} INFO - [2021-06-06 23:58:28,947] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:58:28,948] {logging_mixin.py:104} INFO - [2021-06-06 23:58:28,948] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 51
    =[ 'Person']
    ^
SyntaxError: invalid syntax
[2021-06-06 23:58:28,948] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:58:28,959] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.019 seconds
[2021-06-06 23:58:59,272] {scheduler_job.py:182} INFO - Started process (PID=5450) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:58:59,273] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:58:59,273] {logging_mixin.py:104} INFO - [2021-06-06 23:58:59,273] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:58:59,275] {logging_mixin.py:104} INFO - [2021-06-06 23:58:59,274] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 51
    =[ 'Person']
    ^
SyntaxError: invalid syntax
[2021-06-06 23:58:59,275] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:58:59,294] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.024 seconds
[2021-06-06 23:59:30,008] {scheduler_job.py:182} INFO - Started process (PID=5529) to work on /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:59:30,009] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/rox_etl_dag.py for tasks to queue
[2021-06-06 23:59:30,009] {logging_mixin.py:104} INFO - [2021-06-06 23:59:30,009] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:59:30,011] {logging_mixin.py:104} INFO - [2021-06-06 23:59:30,010] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/rox_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/rox_etl_dag.py", line 51
    =[ 'Person']
    ^
SyntaxError: invalid syntax
[2021-06-06 23:59:30,011] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/rox_etl_dag.py
[2021-06-06 23:59:30,022] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/rox_etl_dag.py took 0.015 seconds
